config/routes.rb
Orangerie::Application.routes.draw do
  
  devise_for :admins

  devise_for :users
  
  resources :home, :connections, :posts
  
  resources :messages do
    collection do
      get :sent
      get :trash
    end
    member do
      get :reply
      put :undestroy
    end
  end
  
  
  resources :users do
    get :trusted
    resources :connections
    resources :messages
    resources :posts do
      resources :comments
    end
    member do
      get :infos
      get :friends
      get :fotos
      get :livestream
    end
  end
  
  root :to => "pages#home"
  

end

app/views/shared/_left_box.html.erb
<img src="/images/rails.png" width="200px" height="200px" class="small-profile-pic">
<p>
	About me:<br/>
	<%= !@user.infos.about_us.nil? ? @user.infos.about_us : "No description yet." %>
</p>
<p>
	My friends:<br/>
	<% unless @user.contacts.empty? %>
		<%= render :partial => "users/friends_list" %>
	<% else %>
		No friends yet.
	<% end %>
</p>
<p>
	<%= send_message_link(@user, image=true) %>
</p>
<p>
	<%= connection_button(@user, current_user) %>
</p>

app/views/shared/_user_navi.html.erb
<ul class="user-navigation">
	<% if current_user?(@user) %>
		<li><%= link_to "Livestream", livestream_user_path(@user) %></li>
	<% end %>	
	<li><%= link_to "Wall", user_path(@user) %></li>
	<li><%= link_to "Infos", infos_user_path(@user) %></li>
	<li><%= link_to "Freunde", friends_user_path(@user) %></li>
	<li><%= link_to "Fotos", fotos_user_path(@user) %></li>
	<% if current_user?(@user) %>
		<li><%= link_to "Messages", messages_path %></li>
	<% end %>
	<% if current_user?(@user) and params[:controller] == "messages" %>
		<li style="float: right"><%= link_to "Trash", trash_messages_path %></li>
		<li style="float: right"><%= link_to "Sent", sent_messages_path %></li>
		<li style="float: right"><%= link_to "Inbox", messages_path %></li>
	<% end %>
</ul>