config/routes.rb
Orangerie::Application.routes.draw do
  
  devise_for :admins

  devise_for :users
  
  resources :home, :connections, :posts
  
  resources :messages do
    collection do
      get :sent
      get :trash
    end
    member do
      get :reply
      put :undestroy
    end
  end
  
  
  resources :users do
    get :trusted
    resources :connections
    resources :messages
    resources :posts do
      resources :comments
    end
    member do
      get :infos
      get :friends
      get :fotos
      get :livestream
    end
  end
  
  root :to => "pages#home"
  

end

app/views/home/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.oauthable? %>
  <%- resource_class.oauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", oauth_authorize_url(resource_name, provider) %><br />
  <% end =%>
<% end -%>