config/routes.rb
Orangerie::Application.routes.draw do
  
  devise_for :admins

  devise_for :users
  
  resources :home, :connections, :posts
  
  resources :messages do
    collection do
      get :sent
      get :trash
    end
    member do
      get :reply
      put :undestroy
    end
  end
  
  
  resources :users do
    get :trusted
    resources :connections
    resources :messages
    resources :posts do
      resources :comments
    end
    member do
      get :infos
      get :friends
      get :fotos
      get :livestream
    end
  end
  
  root :to => "pages#home"
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend ActivityLogger
  belongs_to :user
  belongs_to :owner, :class_name => "User", :foreign_key => "wall_id"
  
  has_many    :comments, :as => :commentable
  
  # association for the livestreams and feeds
  has_many :activities, :foreign_key => "item_id", :dependent => :destroy,
                          :conditions => "item_type = 'Post'"
  
  validates_presence_of :body, :message => "can't be blank"
  validates_length_of :body, :within => 2..140, :message => "between 3-140 letters"
  
  after_create {|post| Post.log_activity(post)}
  
  private
    class << self
        def log_activity(post)
          activity = Activity.create!(:item => post, :user => post.user)
          add_activities(:activity => activity, :user => post.user, :include_user => post.user)
        end
    end
end

app/controllers/posts_controller.rb
# NOTE: We use "posts" for both forum topic posts and blog posts,
# There is some trickery to handle the two in a unified manner.
class PostsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :trusted
  before_filter :authorize_create, :except => [:index, :destroy]
  before_filter :authorize_destroy, :except => [:index, :create]
  
  def create
    @post = current_user.posts.build(params[:post])
    
    if @post.save
      flash[:success] = "Wall post created."
      redirect_to user_path(@post.owner)
    else
      flash[:error] = "Your wall post can not be blank."
      redirect_to user_path(@post.owner)
    end
  end
  
  def destroy
    if @post.destroy
      flash[:success] = "Post destroyed"
      respond_to do |format|
        format.html { redirect_to user_path(@post.wall_id) }
      end
    else  
      flash[:error] = "The wall post was not deleted."
      redirect_to user_path(@post.owner)
    end
  end
  
  private
  
      ## Before filters
      # Verify the person is authorized to create a post.
      def authorize_create
        wall_owner = User.find(params[:post][:wall_id])
        unless is_friend?(wall_owner) or own_wall?(wall_owner)
          redirect_to user_path(wall_owner)
        end
      end
      
      def authorize_destroy
        @post = Post.find(params[:id])
        redirect_to user_path(@post.owner) unless @post.user == current_user or @post.owner == current_user
      end
      
      def is_friend?(wall_owner)
        Connection.accepted?(current_user, wall_owner)
      end
      
      def own_wall?(wall_owner)
        current_user == wall_owner
      end
      
      def trusted
        redirect_to trusted_user_path(current_user) unless current_user.trusted
      end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.erb
<% unless @stream.blank? %>
	<% @stream.each do |post|%>
	<% if post.class.to_s == "Activity" %>
	 	<% livestream_message(post) %>
	<% else %>
	<div id="user-show-post">
		<% if current_user?(post.user) or current_user?(post.owner)%>
			<%= button_to "X", user_post_path(@user.id, post.id), 
  			        :method => :delete, :title => I18n.t('users.posts.delete'),
  			        :confirm => "?", 
  					:remote => true,
 					:class => "destroy", %>
		<% end %>
		<img src="/images/rails.png" width="30px" height="30px" class="inline-profile-pic">
		<%= link_to post.user.name, user_path(post.user) %> wrote <%= distance_of_time_in_words_to_now(post.created_at) %> ago:
		<p class="user-show-post-content">"<%= post.body %>"</p>
		
		<div id="user-show-post-comments">
		<a href="#" class="show-comment" data-id="<%= post.id %>">[+] show <%= post.comments.count %> comments</a>
			<div id="user-show-comment" data-id="<%= post.id %>">
				<% unless post.comments.blank? %>
					<% post.comments.each do |comment| %>
						<div class="comment">
							<table border="0" cellspacing="0" cellpadding="0">
								<tr>
									<td class="user-pic"><img src="/images/rails.png" width="30px" height="30px" class="inline-profile-pic"></td>
									<td class="comment-body">
										<% if current_user?(comment.user) or current_user?(@user)%>
											<%= button_to "X", user_post_comment_path(@user.id, comment.commentable.id, comment.id), 
								  			        :method => :delete, :title => I18n.t('users.comments.delete'),
								  			        :confirm => "?", 
								  					:remote => true,
								 					:class => "destroy", %>
										<% end %>
										<%= comment.body %><br/>
										<small><%= distance_of_time_in_words_to_now(comment.created_at) %>
								 		ago by <%= link_to(comment.user.name, comment.user) %></small>
									</td>
								</tr>
							</table>
						</div>
					<% end %>
				<% end %>	
				<div id="comment-form">
					<% semantic_form_for(Comment.new, 
								:url => user_post_comments_path(post.user, post),  
								:html => {:method => :post}) do |f| %>
						<img src="/images/rails.png" width="30px" height="30px" class="inline-profile-pic">
						<%= f.inputs do %>
							<%= f.input :body, :label => false %>
							<%= f.commit_button 'Senden' %>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
		
		<% if current_user?(@user) %>
			<%= button_to "Delete Post", post_path(post), 
			                  :method => :delete, :title => "Delete Post",:remote => true %>
		<% end %>
	</div>	
	<% end %>
<% end %>
	
	
<% else %>
	No wall posts yet.
<% end %>
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
	$('.comment-link').click(function(){
		var post_id = $(this).parent().attr('class');
		$('.formtastic /users/'+post_id).fadeIn();
		return false;
	});
	$('.show-comment').click(function(){
		var post_id = $(this).attr("data-id");
		$('div[data-id='+post_id+']').fadeIn();
		return false;
	});
});
</script>

app/views/posts/_new.html.erb
<% if is_friend?(@user) or current_user?(@user)%>
	<%= semantic_form_for(@user.posts.new, :html => {:method => :post} ) do |f| %>
		<%= f.inputs  do %>
			<%= f.input :body, :label => false,  :required => false %>
			<%= f.input :wall_id, :as => :hidden, :value => @user.id %>
			<%= f.commit_button 'Senden' %>
		<% end %>
	<% end %>
<% end %>

app/views/posts/new.html.erb
<% if is_friend?(@user) or own_profile?%>
	<%= semantic_form_for(new_user_post_path(@user), :html => {:method => :post} ) do |f| %>
		<%= f.inputs  do %>
			<%= f.input :body, :label => 'Body' %>
			<%= f.input :wall_id, :as => :hidden, :value => @user.id %>
			<%= f.commit_button 'Senden' %>
		<% end %>
	<% end %>
<% end %>